#!/usr/bin/env python3

import os
import sys
import yaml
import shutil
import subprocess 
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

@dataclass
class PrepConfig:
    """Class for spefifying the configuration of a solvation prep with tleap (Ambertools)."""
    name: str
    leaprc_mol: str
    leaprc_sol: str
    frcmod: Path
    mol2: Path
    water_model: str
    buffer: float
    input_dir: Path
    counterion_num: int = 0
    frcmod_ion: Optional[str] = None
    counterion: Optional[str] = None
    prefix: Optional[str] = None

def load_config(yaml_path: Path) -> PrepConfig:
    
    data = yaml.safe_load(yaml_path.read_text())
    
    cfg = PrepConfig(
        name=data["name"],
        leaprc_mol=data["leaprc_mol"],
        leaprc_sol=data["leaprc_sol"],
        frcmod_ion=data["frcmod_ion"],
        frcmod=Path(data["frcmod"]),
        mol2=Path(data["mol2"]),
        water_model=data.get("water_model"),
        buffer=float(data.get("buffer")),
        counterion=data.get("counterion"),
        counterion_num=int(data.get("counterion_num")),
        input_dir=Path(data["input_dir"]),
        prefix=data.get("prefix", "solv"),
    )

    return cfg

def write_tleap_in(cfg: PrepConfig) -> Path:

    base_dir = cfg.input_dir.parent
    prep_dir = base_dir / f"{cfg.prefix}_{cfg.buffer:.1f}" / "prep"
    prep_dir.mkdir(parents=True, exist_ok=True)

    frcmod_name = cfg.frcmod.name
    mol2_name = cfg.mol2.name

    frcmod_src = cfg.input_dir / frcmod_name
    mol2_src = cfg.input_dir / mol2_name
    
    # Existence of input checks
    if not frcmod_src.exists():
        raise FileNotFoundError(f"Missing in input_dir: {frcmod_src}")
    if not mol2_src.exists():
        raise FileNotFoundError(f"Missing in input_dir: {mol2_src}")
    
    # Copy inputs to prep dir to run tleap in
    shutil.copy2(frcmod_src, prep_dir / frcmod_name)
    shutil.copy2(mol2_src, prep_dir / mol2_name)

    tleap_in = prep_dir / "tleap.in"

    addions_block = ""
    if cfg.counterion_num > 0:
        addions_block = f'addions sys {cfg.counterion} {cfg.counterion_num}\n'

    text = f"""\
# Auto-generated by qmmd prep.py
# System: {cfg.name}

source {cfg.leaprc_mol}
source {cfg.leaprc_sol}

# Ions (Joung-Cheatham for TIP3P)
loadamberparams {cfg.frcmod_ion}

# Molecule params
loadamberparams {frcmod_name}
sys = loadmol2 {mol2_name}

# Solvate (buffer in Angstrom)
solvatebox sys {cfg.water_model} {cfg.buffer}

# Counterions
{addions_block.rstrip()}

saveamberparm sys {cfg.prefix}.parm7 {cfg.prefix}.rst7
quit
"""
    tleap_in.write_text(text)
    return tleap_in


def require_amber() -> Path:
    amberhome = os.environ.get("AMBERHOME")
    if not amberhome:
        raise RuntimeError("AMBERHOME is not set.")

    tleap = shutil.which("tleap")
    if not tleap:
        raise RuntimeError("tleap not found in PATH. Did you load Amber?")

    tleap_path = Path(tleap).resolve()

    expected = Path(amberhome).resolve() / "bin" / "tleap"
    if tleap_path != expected:
        raise RuntimeError(
            f"tleap mismatch:\n"
            f"  PATH tleap: {tleap_path}\n"
            f"  AMBERHOME: {amberhome}\n"
            f"  expected: {expected}\n"
            f"Fix by re-loading the correct Amber module."
        )

    return tleap_path

def run_tleap(cfg: PrepConfig, tleap_in: Path) -> None: 
    
    prep_dir = tleap_in.parent
    out_path = prep_dir / "tleap.out"

    with out_path.open("w") as f:
        tleap = require_amber()
        subprocess.run(
            [str(tleap), "-f", tleap_in.name],
            cwd=prep_dir,
            stdout=f,
            stderr=subprocess.STDOUT,
            check=True,
        )

def run_prep(yaml_path):
    cfg = load_config(yaml_path)
    tleap_in = write_tleap_in(cfg)
    run_tleap(cfg, tleap_in)

    prep_dir = tleap_in.parent

    # Freeze config for reproducibility (in the prep dir)
    (prep_dir / "spec.yaml").write_text(yaml_path.read_text())

    parm7 = prep_dir / f"{cfg.prefix}.parm7"
    rst7 = prep_dir / f"{cfg.prefix}.rst7"
    if not parm7.exists() or parm7.stat().st_size == 0:
        raise RuntimeError(f"Missing/empty output: {parm7}")
    if not rst7.exists() or rst7.stat().st_size == 0:
        raise RuntimeError(f"Missing/empty output: {rst7}")

    print(f"OK: wrote {parm7.name} and {rst7.name} in {prep_dir}")

def main() -> None:
    if len(sys.argv) != 2:
        print("Usage: python3 prep.py prep.yaml", file=sys.stderr)
        raise SystemExit(2)

    yaml_path = Path(sys.argv[1]).resolve()
    cfg = load_config(yaml_path)

    tleap_in = write_tleap_in(cfg)
    run_tleap(cfg, tleap_in)

    prep_dir = tleap_in.parent

    # Freeze config for reproducibility (in the prep dir)
    (prep_dir / "spec.yaml").write_text(yaml_path.read_text())

    parm7 = prep_dir / f"{cfg.prefix}.parm7"
    rst7 = prep_dir / f"{cfg.prefix}.rst7"
    if not parm7.exists() or parm7.stat().st_size == 0:
        raise RuntimeError(f"Missing/empty output: {parm7}")
    if not rst7.exists() or rst7.stat().st_size == 0:
        raise RuntimeError(f"Missing/empty output: {rst7}")

    print(f"OK: wrote {parm7.name} and {rst7.name} in {prep_dir}")


if __name__ == "__main__":
    main()
