#!/usr/bin/env python3

import os
import sys
import yaml
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class CpptrajPostConfig:
    system: str
    buffer: float
    prefix: str
    job_name: str

    counterion: str = "Cl-"
    solute_mask: str = ":1"
    nclosest: int = 999999
    delete_h: str = "H1"  # or H2 (or H= if you later decide)
    input_source: str = "mdequil"  # or "prep"


def find_repo_root(start: Path) -> Path:
    p = start.resolve()
    for parent in [p] + list(p.parents):
        if (parent / "pyproject.toml").exists():
            return parent
    raise RuntimeError(f"Could not find repo root (pyproject.toml) starting from {start}")


def system_base_dir(cfg: CpptrajPostConfig, repo_root: Path) -> Path:
    return repo_root / "systems" / cfg.system / f"{cfg.prefix}_{cfg.buffer:.1f}"


def prep_dir(cfg: CpptrajPostConfig, repo_root: Path) -> Path:
    return system_base_dir(cfg, repo_root) / "prep"


def run_dir(cfg: CpptrajPostConfig, repo_root: Path) -> Path:
    return system_base_dir(cfg, repo_root) / cfg.job_name


def out_dir(cfg: CpptrajPostConfig, repo_root: Path) -> Path:
    return system_base_dir(cfg, repo_root) / "salt"


def load_config(yaml_path: Path) -> CpptrajPostConfig:
    data = yaml.safe_load(yaml_path.read_text())
    return CpptrajPostConfig(
        system=data["system"],
        buffer=float(data["buffer"]),
        prefix=data.get("prefix", "solv"),
        job_name=data.get("job_name", "mdequil"),
        counterion=data.get("counterion", "Cl-"),
        solute_mask=data.get("solute_mask", ":1"),
        nclosest=int(data.get("nclosest", 999999)),
        delete_h=data.get("delete_h", "H1"),
        input_source=data.get("input_source", "mdequil"),
    )


def require_cpptraj() -> Path:
    amberhome = os.environ.get("AMBERHOME")
    if not amberhome:
        raise RuntimeError("AMBERHOME is not set. Did you load Amber?")

    cpptraj = shutil.which("cpptraj")
    if not cpptraj:
        raise RuntimeError("cpptraj not found in PATH. Did you load Amber?")

    cpptraj_path = Path(cpptraj).resolve()
    expected = Path(amberhome).resolve() / "bin" / "cpptraj"
    if cpptraj_path != expected:
        raise RuntimeError(
            f"cpptraj mismatch:\n"
            f"  PATH cpptraj: {cpptraj_path}\n"
            f"  AMBERHOME: {amberhome}\n"
            f"  expected: {expected}\n"
            f"Fix by re-loading the correct Amber module."
        )
    return cpptraj_path


def run_cpptraj(cpptraj_in: Path) -> None:
    cpptraj = require_cpptraj()
    out_path = cpptraj_in.with_suffix(".out")
    with out_path.open("w") as f:
        subprocess.run(
            [str(cpptraj), "-i", cpptraj_in.name],
            cwd=cpptraj_in.parent,
            stdout=f,
            stderr=subprocess.STDOUT,
            check=True,
        )


def write_cpptraj_1(cfg: CpptrajPostConfig, repo_root: Path) -> Path: 
    pdir = prep_dir(cfg, repo_root)
    rdir = run_dir(cfg, repo_root)
    output_dir = out_dir(cfg, repo_root)
    output_dir.mkdir(parents=True, exist_ok=True)

    parm7 = pdir / f"{cfg.prefix}.parm7"

    if cfg.input_source == "mdequil":
        traj = rdir / "equil-npt.nc"
    else:
        traj = pdir / f"{cfg.prefix}.rst7"

    cppin = output_dir / "cpptraj_1.in"
    cppin.write_text(
        f"""\
# Auto-generated by salt.py
# System: {cfg.system}  buffer={cfg.buffer:.1f}  prefix={cfg.prefix}  job={cfg.job_name}

# block 1: autoimage
parm {parm7}
trajin {traj}
autoimage
trajout production.autoimaged.nc netcdf
run

# block 2: extract last frame (autoimaged)
clear trajin
trajin production.autoimaged.nc lastframe
trajout last_autoimaged.rst7 restart
run

# block 3: strip ion and write last frame coords
clear trajin
trajin last_autoimaged.rst7
strip :{cfg.counterion}
trajout last_no_ion.rst7 restart
run

# block 4: strip ion from topology and write stripped parm
clear parm
clear trajin
parm {parm7}
parmstrip :{cfg.counterion}
parmwrite out no_ion.parm7
run

# block 5: closest list (last data line = furthest entry in this ordering)
clear trajin
clear parm
parm no_ion.parm7
trajin last_no_ion.rst7
closest {cfg.nclosest} {cfg.solute_mask} first closestout closest_waters.dat
run
quit
"""
    )
    return cppin


def parse_furthest_resid(closest_path: Path) -> int:
    """
    Column 2 is the RESID of the furthest water molecule.
    Parse the last data line: Frame  RESID  Distance  FirstAtom#
    """
    if not closest_path.exists() or closest_path.stat().st_size == 0:
        raise RuntimeError(f"Missing/empty: {closest_path}")

    last = None
    for line in closest_path.read_text().splitlines():
        parts = line.split()
        if len(parts) == 4 and parts[0].isdigit():
            last = parts

    if last is None:
        raise RuntimeError(f"No data lines found in {closest_path}")

    resid = last[1]
    if not resid.isdigit():
        raise RuntimeError(f"Expected integer resid in col2, got '{resid}' from line: {last}")

    return int(resid)


def write_cpptraj_2(cfg: CpptrajPostConfig, repo_root: Path, resid: int) -> Path:
    output_dir = out_dir(cfg, repo_root)
    output_dir.mkdir(parents=True, exist_ok=True)

    cppin = output_dir / "cpptraj_2.in"
    cppin.write_text(
        f"""\
# Auto-generated by salt.py
# Delete one H from furthest water residue {resid} to make the hydroxide anion

# block 1: make the coordinates files
parm no_ion.parm7
trajin last_no_ion.rst7
strip :{resid}@{cfg.delete_h}
trajout ready.rst7 rst7
trajout ready.xyz xyz
run

# block 2: make the topology file
clear trajin
clear parm
parm no_ion.parm7
parmstrip :{resid}@{cfg.delete_h}
parmwrite out ready.parm7
run

quit
"""
    )
    return cppin


def run_salt(yaml_path: Path) -> None:
    cfg = load_config(yaml_path)

    repo_root = find_repo_root(yaml_path)
    pdir = prep_dir(cfg, repo_root)
    rdir = run_dir(cfg, repo_root)
    output_dir = out_dir(cfg, repo_root)

    # Validate inferred inputs
    parm7 = pdir / f"{cfg.prefix}.parm7"
    if cfg.input_source == "mdequil":
        traj = rdir / "equil-npt.nc"
    else:
        traj = pdir / f"{cfg.prefix}.rst7"

    if not parm7.exists() or parm7.stat().st_size == 0:
        raise RuntimeError(f"Missing/empty inferred input parm7: {parm7}")
    if not traj.exists() or traj.stat().st_size == 0:
        raise RuntimeError(f"Missing/empty inferred input: {traj}")

    # Freeze YAML in output dir (reproducibility)
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "spec.yaml").write_text(yaml_path.read_text())

    # Stage 1
    cpp1 = write_cpptraj_1(cfg, repo_root)
    run_cpptraj(cpp1)

    # Parse furthest resid from stage 1 output
    closest_path = output_dir / "closest_waters.dat"
    resid = parse_furthest_resid(closest_path)
    print(f"[INFO] Furthest water resid (closest_waters.dat col2) = {resid}")

    # Stage 2
    cpp2 = write_cpptraj_2(cfg, repo_root, resid)
    run_cpptraj(cpp2)

    # Validate outputs
    ready_xyz = output_dir / "ready.xyz"
    if not ready_xyz.exists() or ready_xyz.stat().st_size == 0:
        raise RuntimeError(f"Missing/empty output: {ready_xyz}")

    print(f"OK: outputs in {output_dir}")
    print(f"OK: wrote ready.xyz and ready.parm7 (deleted :{resid}@{cfg.delete_h})")


def main() -> None:
    if len(sys.argv) != 2:
        print("Usage: python3 salt.py configs/SYS/salt.yaml", file=sys.stderr)
        raise SystemExit(2)
    run_salt(Path(sys.argv[1]).resolve())


if __name__ == "__main__":
    main() 
